name: ServerManager
version: '${project.version}'
main: com.fameless.servermanager.ServerManager
api-version: '1.20'
author: Fameless9

commands:
  rank:
  mute:
  unmute:
  timeout:
  hideab:
  perm:
  smhelp:
    aliases: sminfo
  vanish:
    aliases: v
  report:
  freeze:
  unfreeze:
  nick:
  whois:
  rename:
  hologram:
  spawnpreset: